In [2]:
import numpy as np
arr = np.array([2,5,6,8], dtype = int)
print(arr)
# [2 5 6 8]
print(type(arr))
# class 'numpy.ndarray'
print(np.result_type(arr))
# int32 
 


[2 5 6 8]
<class 'numpy.ndarray'>
int32


In [4]:
 
''' Creation of an array with step size 1.33 between 0 - 10 '''
print(np.arange(0, 10, 1.33, dtype = np.float64))



[0.   1.33 2.66 3.99 5.32 6.65 7.98 9.31]


In [5]:
''' Creation of an array with total 5 values between 0 - 160 '''
print(np.linspace(0, 160, 5, dtype = np.float64))

[  0.  40.  80. 120. 160.]


In [6]:
 
''' Method I: Using array and reshape to convert array into matrix '''
print(np.array([5,6,8,45,12,52]).reshape(2,3))
 

[[ 5  6  8]
 [45 12 52]]


In [11]:

''' Method III: Using misc. functions '''
print(np.eye(3)) # Identity matrix

print( np.zeros( (4,3) ) )

print(np.ones( (3,3), dtype = np.float64 ))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
''' Method II: Using matrix function '''
print(np.matrix([[1,2],[3,4]]))

[[1 2]
 [3 4]]


In [13]:
import numpy as np

arr1 = np.ones(10)
arr2 = np.arange(10, dtype = np.float64)
arr3 = arr1 + arr2
print(np.result_type(arr1))
print(np.result_type(arr3))
 

float64
float64


In [14]:
arr = np.arange(4)
arr.reshape(2,2)
print(arr.shape)

(4,)


In [15]:
arr = np.arange(4).reshape(4,-1)
print(arr.shape)

(4, 1)


In [16]:
S_X = np.array([[2, 5, 6, 5],
               [4, 8, 6, 5]])
print(S_X)

[[2 5 6 5]
 [4 8 6 5]]


In [17]:
S_Y = np.array([[6, 7, 5, 9],
               [7, 5, 6, 4]])
print(S_Y)

[[6 7 5 9]
 [7 5 6 4]]


In [18]:
 
print(S_Y - S_X)


[[ 4  2 -1  4]
 [ 3 -3  0 -1]]


In [19]:
print(S_X < 2)

[[False False False False]
 [False False False False]]


In [20]:
twos_mat = np.ones((2, 4)) * 2
print(np.less(S_Y, twos_mat))

[[False False False False]
 [False False False False]]


In [2]:
import numpy as  np
print(None == None)
print(np.nan == np.NaN)
print(np.nan == np.nan)

True
False
False
